version: '3.8'

services:
 vtn-server:
  build:
   context: "./apps/server_and_backend"
  ports:
   - 4000:4000
   - 4001:4001
   - 4002:4002
   - 9229:9229
  env_file:
    - ./config/dockerlocal.env
  environment:
   - SERVER_PORT=4000
   - CONNECTIONSTRING=mongodb://mongo:27017/vote-the-news
  volumes:
   - server:/data/server
  command: npm run debug

 mongo:
  image: mongo:5.0.6
  volumes:
   - mongodb:/data/db
   - mongodb_config:/data/configdb

 vtn-react-app:
  build:
   context: "./apps/react_app"
   args:
    - REACT_APP_SERVER_URL=http://localhost:4000/
    - REACT_APP_WEBSOCKET_URL_NOTIF=ws://localhost:4001/
    - REACT_APP_WEBSOCKET_URL_VOTES=ws://localhost:4002/
  ports:
   - 80:80
   - 443:443
  environment:
   - SERVER_PORT=80
  volumes:
    - ./nginx/conf/:/etc/nginx/conf.d/:ro
    - ./certbot/www/:/var/www/certbot/:ro
    - ./certbot/conf/:/etc/nginx/ssl/:ro

 certbot:
  image: certbot/certbot:latest
  volumes:
    - ./certbot/www/:/var/www/certbot/:rw
    - ./certbot/conf/:/etc/letsencrypt/:rw

volumes:
 mongodb:
 mongodb_config:
 server: