version: '3.8'

services:
 vtn-server:
  build:
   context: .
  ports:
   - 4000:4000
   - 9229:9229
  environment:
   - SERVER_PORT=4000
   - CONNECTIONSTRING=mongodb://mongo:27017/vote-the-news
  volumes:
   - ./:/server_and_backend
  command: npm run debug

 mongo:
  image: mongo:5.0.6
#   ports:
#    - 27017:27017
  volumes:
   - mongodb:/data/db
   - mongodb_config:/data/configdb
volumes:
 mongodb:
 mongodb_config: