name: Build & Deploy

on:
  push:
    branches: 
      - main

jobs:
  push_to_droplet:
    runs-on: ubuntu-latest
    steps:
      - name: Create SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > "$SSH_KEY_PATH"
          sudo chmod 600 "$SSH_KEY_PATH"
          echo "$SSH_KNOWN_HOST" > ~/.ssh/known_hosts
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          SSH_KNOWN_HOST: ${{secrets.SSH_KNOWN_HOSTS}}
          SSH_KEY_PATH: ${{ github.workspace }}/../private.key
      - name: Connect to Droplet, write timestamp, and close connection
        run: |
          ssh -i "$SSH_KEY_PATH" root@"$SSH_KNOWN_HOST"
          date >> timestamp.txt
          exit
        shell: bash
        env:
          SSH_KNOWN_HOST: ${{secrets.SSH_KNOWN_HOSTS}}
          SSH_KEY_PATH: ${{ github.workspace }}/../private.key