
name: Build & Deploy

on:
  push:
    branches: 
      - main
      - dev_deploy

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v3
      - name: Create deploy_meta.env
        run: |
          echo \
          "GITHUB_SHA="$GITHUB_SHA \
          "\nGITHUB_RUN_ID="$GITHUB_RUN_ID \
          "\nGITHUB_RUN_NUMBER="$GITHUB_RUN_NUMBER \
          "\nIMAGES_TAG="$(echo $GITHUB_SHA | head -c7) \
          > deploy_meta.env
      - name: Build images
        run: |
          docker build -t focall/vtn_server:$(echo $GITHUB_SHA | head -c7) apps/server_and_backend/ 
          docker build --build-arg REACT_APP_SERVER_URL=http://104.248.194.185:4000/ -t focall/vtn_react_app:$(echo $GITHUB_SHA | head -c7) apps/react_app/
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push Docker image to Docker Hub
        run: |
          docker push focall/vtn_server:$(echo $GITHUB_SHA | head -c7)
          docker push focall/vtn_react_app:$(echo $GITHUB_SHA | head -c7)
      - name: Upload deploy_meta.env
        uses: actions/upload-artifact@v3
        with:
          name: deploy metadata
          path: deploy_meta.env
  
  deploy:
    needs: build_and_push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v3
      - name: Download deploy_meta.env
        uses: actions/download-artifact@v3
        with:
          name: deploy metadata
      - name: List all files in folder
        run: ls -a
      - name: Copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_KNOWN_HOSTS }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "docker-compose.production.yml,deploy_meta.env,config/digitalocean.env"
          target: "vote_the_news"
          rm: true
      - name: Execute remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_KNOWN_HOSTS }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            date >> timestamp.txt
            cd vote_the_news
            docker ps -aq | xargs docker stop | xargs docker rm
            docker images -a | xargs docker rmi
            docker compose -f docker-compose.production.yml --env-file deploy_meta.env up -d