
name: Build & Deploy

on:
  push:
    branches: 
      - main
      - dev_deploy

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v3
      - name: Create deploy_meta.env
        run: |
          echo "GITHUB_SHA="$GITHUB_SHA > deploy_meta.env
          echo "GITHUB_RUN_ID="$GITHUB_RUN_ID >> deploy_meta.env
          echo "GITHUB_RUN_NUMBER="$GITHUB_RUN_NUMBER >> deploy_meta.env
          echo "IMAGES_TAG="$(echo $GITHUB_SHA | head -c7) >> deploy_meta.env
      - name: Build images server
        run: |
          docker build -t focall/vtn_server:$(echo $GITHUB_SHA | head -c7) apps/server_and_backend/ 
      - name: Build images react app for certification
        run: |
          docker build --build-arg REACT_APP_SERVER_URL=https://server.votethenews.com:4000/ --build-arg REACT_APP_WEBSOCKET_URL_NOTIF=ws://server.votethenews.com:4001/ --build-arg REACT_APP_WEBSOCKET_URL_VOTES=ws://server.votethenews.com:4002/ -t focall/vtn_react_app_certif:$(echo $GITHUB_SHA | head -c7) apps/react_app/
      - name: Add configuration to serve app on port 443 in nginx
        run: |
          cat apps/react_app/.nginx/nginx_certif.conf >> apps/react_app/.nginx/nginx.conf
      - name:  Build images react app
        run: |
          docker build --build-arg REACT_APP_SERVER_URL=https://server.votethenews.com:4000/ --build-arg REACT_APP_WEBSOCKET_URL_NOTIF=ws://server.votethenews.com:4001/ --build-arg REACT_APP_WEBSOCKET_URL_VOTES=ws://server.votethenews.com:4002/ -t focall/vtn_react_app:$(echo $GITHUB_SHA | head -c7) apps/react_app/
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push Docker image to Docker Hub
        run: |
          docker push focall/vtn_server:$(echo $GITHUB_SHA | head -c7)
          docker push focall/vtn_react_app_certif:$(echo $GITHUB_SHA | head -c7)
          docker push focall/vtn_react_app:$(echo $GITHUB_SHA | head -c7)
      - name: Upload deploy_meta.env
        uses: actions/upload-artifact@v3
        with:
          name: deploy metadata
          path: deploy_meta.env
  
  scp_docker_env:
    needs: build_and_push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v3
      - name: Download deploy_meta.env
        uses: actions/download-artifact@v3
        with:
          name: deploy metadata
      - name: Copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_KNOWN_HOSTS }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "docker-compose.production.yml,deploy_meta.env,config/digitalocean.env"
          target: "vote_the_news"

  deploy:
    needs: scp_docker_env
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v3
      - name: Execute remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_KNOWN_HOSTS }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            date >> timestamp.txt
            cd vote_the_news
            docker ps -aq | xargs docker stop | xargs docker rm
            docker images -a | xargs docker rmi
            docker compose -f docker-compose.production.yml --env-file deploy_meta.env up -d vtn-server -d mongo -d vtn-react-app

# docker compose -f docker-compose.production.yml --env-file deploy_meta.env exec vtn-react-app nginx -s reload