name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-server:

    defaults:
      run:
        working-directory: apps/server_and_backend

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test